### ISSUE TITLE
Umbrella IS consistency tasks

### ISSUE THREAD

**Issue by rayrutjes** [algolia/vue-instantsearch#333]
This issue lists all tasks regarding having consistent DOM and components naming across our InstantSearch libraries.

Clear: 
- [ ] Rename to "ClearAll"
- [ ] Update DOM

TreeMenu:
- [ ] Rename to "HierarchicalMenu"
- [ ] Update DOM

Highlight:
- [ ] Update DOM

Snippet:
- [ ] Update DOM

Results:
- [ ] Rename to "Hits"
- [ ] Update DOM

ResultsPerPageSelector:
- [ ] Rename to "HitsPerPageSelector"
- [ ] Update DOM

Input:
- [ ] Remove component

Menu:
- [x] Create component (#326)

NoResults:
- [ ] Rename to "NoHits"

PriceRange:
- [ ] Rename to "RangeInput"
- [ ] Update DOM

Pagination:
- [ ] Update DOM

SearchBox: 
- [ ] Update DOM

SortBySelector:
- [ ] Update DOM

Rating:
- [ ] Rename to "StarRating"
- [ ] Update DOM

Stats:
- [ ] Update DOM

Toggle
- [ ] Create component (#279)

**Comment by Haroenv** [comment]
solved in a different way in #416
